import type { CollectionCenter } from "../../domain/collection-center";

/**
 * Centros de acopio oficiales publicados tras el sismo M7.4
 * (epicentro San José del Palmar, Chocó, 2026-08-10).
 * Fuentes: Alcaldías / Cruz Roja / ABACO / cobertura El Tiempo–El Espectador
 * (2026-08-10/11). Coordenadas aproximadas de hitos públicos.
 */
export const COLOMBIA_QUAKE_COLLECTION_CENTERS: readonly CollectionCenter[] = [
  {
    id: "co-static-cali-jairo-varela",
    name: "Plazoleta Jairo Varela",
    manager: "Alcaldía de Cali",
    location: {
      address: "Plazoleta Jairo Varela, Centenario",
      latitude: 3.4550187,
      longitude: -76.5348007,
    },
    city: "Cali",
    country: "Colombia",
    accepts: ["water", "tools", "blankets", "food"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description:
      "Prioridad: agua, guantes, gafas, cascos y colchonetas para rescate. Zona afectada (Valle).",
  },
  {
    id: "co-static-cali-banco-alimentos",
    name: "Banco de Alimentos de Cali",
    manager: "Fundación Arquidiocesana Banco de Alimentos",
    location: {
      address: "Calle 24 #6-103",
      latitude: 3.4516,
      longitude: -76.5319,
    },
    city: "Cali",
    country: "Colombia",
    accepts: ["food", "water"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Recepción de víveres / alimentos no perecederos. Zona afectada (Valle).",
  },
  {
    id: "co-static-cali-huv-sangre",
    name: "Hospital Universitario del Valle — donación de sangre",
    manager: "HUV Evaristo García",
    location: {
      address: "Calle 5, Nuevo San Fernando",
      latitude: 3.4301834,
      longitude: -76.5454401,
    },
    city: "Cali",
    country: "Colombia",
    accepts: ["blood"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Donación de sangre (todos los grupos). Zona afectada (Valle).",
  },
  {
    id: "co-static-buenaventura-banco-alimentos",
    name: "Banco de Alimentos de Buenaventura",
    manager: "Banco de Alimentos",
    location: {
      address: "Avenida Simón Bolívar #47C-70 (Colegio Seminario)",
      latitude: 3.8801,
      longitude: -77.0312,
    },
    city: "Buenaventura",
    country: "Colombia",
    accepts: ["food", "water"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description:
      "Recolección de alimentos. Verificar punto alterno si la sede principal sigue en evaluación.",
  },
  {
    id: "co-static-pereira-cafe-ormaza",
    name: "CAFE Ormaza (Centro de Atención)",
    manager: "Alcaldía de Pereira",
    location: {
      address: "Calle 3 bis #5-38",
      latitude: 4.8133,
      longitude: -75.6961,
    },
    city: "Pereira",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Uno de los siete CAFE habilitados en Pereira tras el sismo. Zona afectada (Risaralda).",
  },
  {
    id: "co-static-pereira-cafe-san-nicolas",
    name: "CAFE San Nicolás (Centro de Atención)",
    manager: "Alcaldía de Pereira",
    location: {
      address: "Carrera 14 bis #28-38",
      latitude: 4.8076591,
      longitude: -75.7038626,
    },
    city: "Pereira",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Centro de Atención CAFE San Nicolás. Zona afectada (Risaralda).",
  },
  {
    id: "co-static-pereira-cafe-comuna-cafe",
    name: "CAFE Comuna del Café",
    manager: "Alcaldía de Pereira",
    location: {
      address: "Carrera 3 con Calle 59A",
      latitude: 4.82,
      longitude: -75.69,
    },
    city: "Pereira",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Centro de Atención CAFE Comuna del Café. Zona afectada (Risaralda).",
  },
  {
    id: "co-static-dosquebradas-banco-alimentos",
    name: "Banco de Alimentos — Dosquebradas (La Badea)",
    manager: "Banco de Alimentos",
    location: {
      address: "Transversal 5 #6-30, La Badea",
      latitude: 4.8394,
      longitude: -75.67,
    },
    city: "Dosquebradas",
    country: "Colombia",
    accepts: ["food", "water"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Punto alterno del Banco de Alimentos (área metropolitana de Pereira).",
  },
  {
    id: "co-static-manizales-banco-alimentos",
    name: "Banco de Alimentos de Manizales",
    manager: "Banco de Alimentos de Manizales",
    location: {
      address: "Calle 49 #27A-85",
      latitude: 5.0689,
      longitude: -75.5174,
    },
    city: "Manizales",
    country: "Colombia",
    accepts: ["food", "water"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Alimentos no perecederos. Zona afectada (Caldas).",
  },
  {
    id: "co-static-manizales-hemocentro",
    name: "Hemocentro del Café",
    manager: "Hemocentro del Café",
    location: {
      address: "Carrera 21 #70-06",
      latitude: 5.0516275,
      longitude: -75.482498,
    },
    city: "Manizales",
    country: "Colombia",
    accepts: ["blood"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Donación de sangre (prioridad O+ y O−). Zona afectada (Caldas).",
  },
  {
    id: "co-static-armenia-banco-alimentos",
    name: "Banco de Alimentos Monseñor Roberto López Londoño",
    manager: "Banco de Alimentos de Armenia",
    location: {
      address: "Armenia, Quindío",
      latitude: 4.5339,
      longitude: -75.6811,
    },
    city: "Armenia",
    country: "Colombia",
    accepts: ["food", "water"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Recepción de víveres. Zona afectada (Quindío).",
  },
  {
    id: "co-static-medellin-banco-arquidiocesano",
    name: "Fundación Banco Arquidiocesano de Alimentos",
    manager: "Campaña Colombia se levanta",
    location: {
      address: "Carrera 52 #30A-97",
      latitude: 6.2308,
      longitude: -75.5908,
    },
    city: "Medellín",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Hub regional cercano (Antioquia) para donaciones hacia zonas afectadas.",
  },
  {
    id: "co-static-medellin-saciar",
    name: "Fundación Saciar",
    manager: "Campaña Colombia se levanta",
    location: {
      address: "Carrera 50 #25-261",
      latitude: 6.235,
      longitude: -75.575,
    },
    city: "Medellín",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: null,
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Hub regional cercano (Antioquia) para donaciones hacia zonas afectadas.",
  },
  {
    id: "co-static-itagui-parque-principal",
    name: "Parque Principal de Itagüí",
    manager: "Consejo Municipal de Juventudes de Itagüí",
    location: {
      address: "Parque Principal",
      latitude: 6.1723858,
      longitude: -75.609416,
    },
    city: "Itagüí",
    country: "Colombia",
    accepts: ["food", "water", "hygiene", "blankets"],
    contact: null,
    schedule: "Verificar horarios del día con la Alcaldía / CMJ",
    status: "active",
    verificationLevel: "official",
    disputed: false,
    description: "Punto de acopio en el Área Metropolitana del Valle de Aburrá.",
  },
];
