import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderBrowserStorageRegistryMarkdown } from "../lib/browser-storage-registry";
import { getAppBuildSha } from "../lib/build-identity";
import { buildSwConfig } from "../lib/sw-cache-policy";

const here = dirname(fileURLToPath(import.meta.url));
const frontendRoot = join(here, "..");
const repoRoot = join(frontendRoot, "..");

const swConfig = buildSwConfig(getAppBuildSha());
const swDest = join(frontendRoot, "public", "sw-config.js");
const swBody = `/* generated by scripts/generate-sw-config.ts — do not edit */
self.__MALLANET_SW_CONFIG = ${JSON.stringify(swConfig, null, 2)};
`;
writeFileSync(swDest, swBody);
console.log(`[generate-sw-config] ${swDest}`);

const docsDir = join(repoRoot, "docs", "platform");
mkdirSync(docsDir, { recursive: true });
const registryDest = join(docsDir, "browser-storage-registry.md");
writeFileSync(registryDest, renderBrowserStorageRegistryMarkdown());
console.log(`[generate-sw-config] ${registryDest}`);
